version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '@angular*'
      - dependency-name: '@nx*'
    open-pull-requests-limit: 20
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
