name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  verify:
    uses: ./.github/workflows/Verify.yml

  deploy:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ./node_modules
            ./nx/cache
          key: yarn-v3-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            yarn-v3-${{ runner.os }}-

      - name: Yarn Install
        run: yarn install

      - name: Build
        run: yarn build --baseHref="/pokedex-md/"

      - name: Trim API
        run: yarn trim

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn deploy
