name: Rebuild Api

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 4'

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Use Node 18
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '18'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./node_modules
          key: yarn-v3-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            yarn-v3-${{ runner.os }}-

      - name: Yarn Install
        run: yarn install

      - name: Build
        run: |
          yarn build:api
          yarn format:all

      - name: Check for changes
        id: git_diff_check
        run: |
          git fetch origin
          git diff --quiet origin/development || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if there were changes
        if: steps.git_diff_check.outputs.changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Poke Bot"
          git config user.email "frango9000@users.noreply.github.com"
          CURRENT_BRANCH=api/$(date +%Y-%U)
          git checkout -b $CURRENT_BRANCH
          git add ./apps/pokedex/src/assets/api
          git commit -m "Chore(api): $CURRENT_BRANCH"
          git push -f origin $CURRENT_BRANCH
          gh pr create --base development --title "Chore(api): $CURRENT_BRANCH" --body "Chore(api): $CURRENT_BRANCH"
