name: 'CI'
run-name: ${{ (github.ref == 'refs/heads/development'  && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.redeploy == 'true' ))) && 'Deploy' || 'Verify' }}

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      redeploy:
        type: boolean
        description: 'Redeploy (only applicable for development branch)'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync PR with target
        if: github.event_name == 'pull_request'
        run: git merge origin/${{ github.event.pull_request.base.ref }}

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            ./nx/cache
          key: yarn-v4-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            yarn-v4-${{ runner.os }}-

      - name: Yarn Install
        run: yarn install

      - name: Prettier
        run: yarn run format:check --all

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn build --baseHref="/pokedex-md/"

      - name: Trim API
        if: (github.ref == 'refs/heads/development'  && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.redeploy == 'true' )))
        run: yarn trim

      - name: Deploy
        if: (github.ref == 'refs/heads/development'  && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.redeploy == 'true' )))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn deploy
