name: Verify

on:
  push:
    branches-ignore:
      - development
  pull_request:
    branches:
      - development
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Sync PR with target
        if: github.event_name == 'pull_request'
        run: git merge ${{ github.event.pull_request.head.sha }}

      - name: Use Node 18
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '18'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./node_modules
          key: yarn-v3-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            yarn-v3-${{ runner.os }}-

      - name: Yarn Install
        run: yarn install

      - name: Prettier
        run: yarn run format:check --all

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build
